import assert from 'node:assert/strict';
import { summarize } from '../profiler/report.js';
globalThis.window = { addEventListener() {} };
globalThis.document = { hidden: false, addEventListener() {} };
globalThis.setInterval = () => 0;
const capture = await import('../profiler/capture.js');
capture.record('disabled', 10);
assert.equal(capture.snapshot().windows.length, 0);
capture.start();
capture.record('audio', 2);
capture.record('audio', 4);
capture.record('invalid', NaN);
let data = capture.snapshot();
let rows = summarize(data);
assert.equal(rows.length, 1);
assert.equal(rows[0].count, 2);
assert.equal(rows[0].totalMs, 6);
assert.equal(rows[0].meanMs, 3);
assert.equal(rows[0].maxMs, 4);
assert.equal(rows[0].p95, 4);
data.windows.length = 0;
assert.equal(capture.snapshot().windows.length, 1);
assert.throws(() => capture.measure('throws', () => { throw Error('test'); }, []));
capture.stop();
assert(summarize(capture.snapshot()).some(row => row.name === 'throws'));
capture.record('stopped', 10);
assert(!summarize(capture.snapshot()).some(row => row.name === 'stopped'));
capture.start();
for (let i = 0; i < 70; i++) { capture.record('bounded', 1); capture.snapshot(); }
assert.equal(capture.snapshot().windows.length, 60);
for (let i = 0; i < 110; i++) capture.diagnostic('test', i);
assert.equal(capture.snapshot().diagnostics.length, 100);
assert.throws(() => summarize({}));
assert.throws(() => summarize({ limitsMs: [1], windows: [{ metrics: { bad: { count: -1 } } }] }));
console.log('PASS: opt-in capture, aggregation, exception timing, bounded storage and validation');
